test: does not have 100% coverage
eq8/redbloom pull request #4
Opened 2016-10-12 16:36 UTC by earayo

- feat: Add new dispatch in test for get default bloomrun.
- fix: Create new validation for get default bloomrun.

2016-10-13 00:40 UTC, bbartolome requested changes
Thanks for the PR! I'll update the related issue to include the expected behaviour if somebody else would like to take over.

2016-10-13 00:40 UTC, bbartolome commented on test/test.unit.js
> +	redbloom.dispatch({ns: 'cmd'});
@earayo, you're on the right track that there should be a dispatch here for an action that was not registered.

However, it doesn't seem to test for the expected behaviour that if an unregistered action was dispatch, it should not change the current state.

If you can update this pull request to reflect the expected behaviour, I'll be happy to merge it. Thanks!

2016-10-13 00:40 UTC, bbartolome commented on index.js
> +				.map(reducer =>	reducer.bind(observable, action));
Additionally, the changes here are not necessary as it was behaving as expected which was to provide a default reducer function if none was found.

From what I could tell, it looks like these changes the behaviour by pushing the default reducer twice.

2016-10-13 15:05 UTC, edwaraco commented on test/test.unit.js
> +	redbloom.dispatch({ns: 'cmd'});
@bbartolome Can you give me an example please?. Thanks!

2016-10-18 16:25 UTC, earayo commented
@bbartolome you can chek again please. Thanks!

2016-11-27 12:43 UTC, bbartolome approved these changes

2016-11-27 12:44 UTC, merged

2016-11-27 12:46 UTC, bbartolome commented
@earayo Thanks for the submission! It looks good and I've merged it. I apologize if it took a while. I've been recently focusing a lot on my other projects and I've just managed to catch up.

Thanks again!